-- Create auth_codes table
CREATE TABLE IF NOT EXISTS auth_codes (
    id SERIAL PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    user_id VARCHAR(255),
    session_token TEXT,
    expires_at TIMESTAMP NOT NULL,
    is_used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Better Auth tables will be generated by the CLI, 
-- but we ensure the auth_codes table exists first.
